version: '3'
services:
  kanboard:
    image: kanboard/kanboard:latest
    restart: always
    ports:
     - "4001:80"
     - "443:443"
    volumes:
     - kanboard_data:/var/www/app/data
     - kanboard_plugins:/var/www/app/plugins
     - kanboard_ssl:/etc/nginx/ssl

  postgres:
      image: postgres:9.5
      restart: always
      environment:
       - "POSTGRES_USER=user1"
       - "POSTGRES_PASSWORD=user1"
       - "POSTGRES_DB=gogs"
       - "POSTGRES_DB=gitea"
       - "POSTGRES_DB=pad"
      volumes:
       - "db-data:/var/lib/postgresql/data"
      networks:
       - gogs
       - gitea

  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./docker-data/gitea:/data
    ports:
      - "4005:3000"
      - "222:22"
    depends_on:
      - postgres

  gogs:
    image: gogs/gogs:latest
    restart: always
    ports:
     - "10022:22"
     - "4000:3000"
    links:
     - postgres
    environment:
     - "RUN_CROND=true"
    networks:
     - gogs
    volumes:
     - ./docker-data/gogs-data:/data
    depends_on:
     - postgres

  murmur:
    image: vimagick/murmur
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
    restart: always

  dudle:
    image: jaydee2202/dudle
    restart: always
    ports:
     - "4003:80"

  # draw:
  #   build: ./draw
  #   restart: always
  #   ports:
  #    - "4004:8080"
  draw:
    image: fjudith/draw.io
    restart: always
    ports:
     - "4004:8443"

  launcher:
    build: ./launcher
    restart: always
    ports:
      - "8080:8080"


networks:
    gogs:
      driver: bridge
    gitea:
      driver: bridge

volumes:
  kanboard_data:
    driver: local
  kanboard_plugins:
    driver: local
  kanboard_ssl:
    driver: local
  db-data:
      driver: local
  gogs-data:
    driver: local
