version: '3'
services:
  kanboard:
    image: kanboard/kanboard:latest
    restart: always
    ports:
     - "4001:80"
     - "443:443"
    volumes:
     - kanboard_data:/var/www/app/data
     - kanboard_plugins:/var/www/app/plugins
     - kanboard_ssl:/etc/nginx/ssl

  postgres:
      image: postgres:9.5
      restart: always
      environment:
       - "POSTGRES_USER=${POSTGRES_USER}"
       - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
       - "POSTGRES_DB=gogs"
       - "POSTGRES_DB=pad"
      volumes:
       - "db-data:/var/lib/postgresql/data"
      networks:
       - gogs

  gogs:
    image: gogs/gogs:latest
    restart: always
    ports:
     - "10022:22"
     - "4000:3000"
    links:
     - postgres
    environment:
     - "RUN_CROND=true"
    networks:
     - gogs
    volumes:
     - "gogs-data:/data"
    depends_on:
     - postgres

  murmur:
    image: vimagick/murmur
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
    restart: always

  dudle:
    image: jaydee2202/dudle
    restart: always
    ports:
     - "4003:80"

  launcher:
      build: ./launcher
      ports:
          - "8080:8080"


networks:
    gogs:
      driver: bridge

volumes:
  kanboard_data:
    driver: local
  kanboard_plugins:
    driver: local
  kanboard_ssl:
    driver: local
  db-data:
      driver: local
  gogs-data:
    driver: local
